name: iOS starter workflow

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          bundle exec pod install --project-directory=PostsApp
          brew install swiftlint
      - name: Lint
        run: bundle exec fastlane linting
        
      - name: Build
        run: bundle exec fastlane build
        
      - name: Unit Tests
        run: bundle exec fastlane test
