name: iOS starter workflow

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
   
      - name: Select Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app/Contents/Developer
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6
          bundler-cache: true 

      - name: Install CocoaPods
        run: |
          gem install cocoapods --no-document
          bundle exec pod install

      - name: Lint
        run: bundle exec fastlane linting
        
      - name: Build
        run: bundle exec fastlane build
        
      - name: Unit Tests
        run: bundle exec fastlane test
